spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #change to none
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
jwt:
  access-token-expiry: 600 # 10 minutes
  refresh-token-expiry: 604800 # 7 days
  secret-key: YXJ6b250b3AtYmFjay1vZmZpY2Utc2VjcmV0LWtleS13aXRoLTBmNjM4MjZhN2E2YzVmNjE5NzNlMWZlODExM2FlODU1MzVjODRjNTY3NDM4ODQ1YTU5ZGQ0MzZkYjRlNmQ5Yjc=

springdoc:
  swagger-ui:
    path: /swagger
